name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker Image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/final-python:latest .
      - name: Build Docker Image
        run: |
            docker push ${{secrets.DOCKERHUB_USERNAME}}/final-python:latest